scan_angle_filter:
  ros__parameters:
    filter1:
      name: angular_bounds_filter
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -2.25  # -60 derece (radyan)
        upper_angle: 2.0   #  60 derece (radyan)

scan_angle_filter_front_l:
  ros__parameters:
    filter1:
      name: angular_bounds_filter_front_l
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -3.14  # -60 derece
        upper_angle: 0.2   #  60 derece

scan_angle_filter_front_r:
  ros__parameters:
    filter1:
      name: angular_bounds_filter_front_r
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 0.0  # -50 derece
        upper_angle: 3.14   #  60 derece
